sudo: false
services:
  - redis-server
  - memcached
  - mongodb
  - couchdb
  - elasticsearch

language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "12"

branches:
  only:
    - master

notifications:
  email:
    - adriano@raiano.ch
